apiVersion: v1
kind: Service
metadata:
  name: short-app-port
spec:
  type: NodePort
  selector:
    components: frontend
  ports:
    - protocol: TCP
      port: 3000 # service port; 
      targetPort: 81 # pod port; 
      nodePort: 31280 # node port
