apiVersion: v1
kind: Pod
metadata:
  name: short-app
  labels:
    components: frontend
spec: 
  containers:
    - name: short-app
      image: antonlarichev/short-app:v1.0
      ports:
        - containerPort: 81
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
      # env:
      #   - name: PORT
      #     value: "8080"
      #   - name: HOST
      #     value: "0.0.0.0"
      # command: ["npm", "start"]
