apiVersion: v1
kind: ConfigMap
metadata:
  name: chatserver-config
data:
  key1: {{ .Release.Name }}
  
  # DB_HOST: "localhost"
  # DB_PORT: "5432"
  # DB_NAME: "chatserver"
  # DB_USER: "postgres"
  # DB_PASSWORD: "postgres"
